title: Thomas Mansour's Website
author: Thomas Mansour
email: tmansour@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  An insight to the life of a quarantined high school senior.

# social links
twitter_username: ToeMass_ # DO NOT include the @ character, or else the build will fail!
github_username:  tmansour1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
